image: python:3.9

stages:
  - analyze
  - unit-test
  - regression-test
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

cache:
  paths:
    - .cache/pip/
    - .venv/

before_script:
  - pip install poetry

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

.analyze:
  stage: analyze

flake8:
  extends: .analyze
  script:
    - poetry install
    - poetry run flake8 -j 1 --statistics src stubs examples tests

black:
  extends: .analyze
  script:
    - poetry install
    - poetry run black --check src tests stubs examples

mypy:
  extends: .analyze
  script:
    - poetry install
    - poetry run mypy --pretty

isort:
  extends: .analyze
  script:
    - poetry install
    - poetry run isort .


.unittest:
  stage: unit-test
  script:
    - poetry install
    - poetry run python -m unittest discover -v -s "tests" -p "test_*.py"

unittest-cp37:
  extends: .unittest
  image: python:3.7
  cache: {}

unittest-cp38:
  extends: .unittest
  image: python:3.8
  cache: {}

unittest-cp39:
  extends: .unittest
  image: python:3.9

.regressiontest:
  stage: regression-test
  script:
    - poetry install
    - poetry run python3 examples/nonlinear.py
    - poetry run python3 examples/f16.py
  rules:
    - if: "$CI_OPEN_MERGE_REQUESTS"

regressiontest-cp37:
  extends: .regressiontest
  image: python:3.7
  cache: {}

regressiontest-cp38:
  extends: .regressiontest
  image: python:3.8
  cache: {}

regressiontest-cp39:
  extends: .regressiontest
  image: python:3.9
  cache: {}

wheel:
  stage: build
  script:
    - poetry build
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v*/'
      when: never

pypi:
  stage: publish
  script:
    - poetry build
    - poetry publish
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v*/'
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz

pages:
  stage: publish
  script:
    - poetry install
    - poetry run sphinx-build -b html docs public
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v*/'
  artifacts:
    paths:
      - public
